export const RS500 = [
  { rank:1,  artist:"The Beatles",       album:"Sgt. Pepper's Lonely Hearts Club Band", year:1967 },
  { rank:2,  artist:"The Beach Boys",    album:"Pet Sounds",                             year:1966 },
  { rank:3,  artist:"Joni Mitchell",     album:"Blue",                                   year:1971 },
  { rank:4,  artist:"Stevie Wonder",     album:"Songs in the Key of Life",               year:1976 },
  { rank:5,  artist:"The Beatles",       album:"Abbey Road",                             year:1969 },
  { rank:6,  artist:"Nirvana",           album:"Nevermind",                              year:1991 },
  { rank:7,  artist:"Fleetwood Mac",     album:"Rumours",                                year:1977 },
  { rank:8,  artist:"Prince",            album:"Purple Rain",                            year:1984 },
  { rank:9,  artist:"Bob Dylan",         album:"Blood on the Tracks",                    year:1975 },
  { rank:10, artist:"Lauryn Hill",       album:"The Miseducation of Lauryn Hill",        year:1998 },
  { rank:11, artist:"The Beatles",       album:"Revolver",                               year:1966 },
  { rank:12, artist:"Michael Jackson",   album:"Thriller",                               year:1982 },
  { rank:13, artist:"Bob Dylan",         album:"Blonde on Blonde",                       year:1966 },
  { rank:14, artist:"Elvis Presley",     album:"The Sun Sessions",                       year:1976 },
  { rank:15, artist:"Miles Davis",       album:"Kind of Blue",                           year:1959 },
  { rank:16, artist:"The Velvet Underground", album:"The Velvet Underground & Nico",     year:1967 },
  { rank:17, artist:"The Rolling Stones",album:"Exile on Main St.",                      year:1972 },
  { rank:18, artist:"Led Zeppelin",      album:"Led Zeppelin IV",                        year:1971 },
  { rank:19, artist:"Bruce Springsteen", album:"Born to Run",                            year:1975 },
  { rank:20, artist:"Marvin Gaye",       album:"What's Going On",                        year:1971 },
  { rank:30, artist:"Radiohead",         album:"OK Computer",                            year:1997 },
  { rank:31, artist:"The Clash",         album:"London Calling",                         year:1979 },
  { rank:32, artist:"Kendrick Lamar",    album:"To Pimp a Butterfly",                    year:2015 },
  { rank:33, artist:"Neil Young",        album:"Harvest",                                year:1972 },
  { rank:40, artist:"Radiohead",         album:"Kid A",                                  year:2000 },
  { rank:41, artist:"Bob Marley",        album:"Exodus",                                 year:1977 },
  { rank:42, artist:"Kanye West",        album:"My Beautiful Dark Twisted Fantasy",      year:2010 },
  { rank:50, artist:"The Doors",         album:"The Doors",                              year:1967 },
  { rank:51, artist:"Frank Ocean",       album:"Blonde",                                 year:2016 },
  { rank:60, artist:"Joy Division",      album:"Unknown Pleasures",                      year:1979 },
  { rank:61, artist:"The Smiths",        album:"The Queen Is Dead",                      year:1986 },
  { rank:70, artist:"Daft Punk",         album:"Discovery",                              year:2001 },
  { rank:71, artist:"Outkast",           album:"Aquemini",                               year:1998 },
  { rank:75, artist:"Sufjan Stevens",    album:"Illinois",                               year:2005 },
  { rank:76, artist:"Wilco",             album:"Yankee Hotel Foxtrot",                   year:2001 },
  { rank:77, artist:"The Strokes",       album:"Is This It",                             year:2001 },
  { rank:78, artist:"Amy Winehouse",     album:"Back to Black",                          year:2006 },
  { rank:79, artist:"LCD Soundsystem",   album:"Sound of Silver",                        year:2007 },
  { rank:80, artist:"Arcade Fire",       album:"Funeral",                                year:2004 },
  { rank:81, artist:"Kendrick Lamar",    album:"good kid, m.A.A.d city",                 year:2012 },
  { rank:82, artist:"Beyonce",           album:"Lemonade",                               year:2016 },
  { rank:83, artist:"Tyler, the Creator",album:"Igor",                                   year:2019 },
  { rank:90, artist:"Fleet Foxes",       album:"Fleet Foxes",                            year:2008 },
  { rank:91, artist:"Bon Iver",          album:"For Emma, Forever Ago",                  year:2008 },
  { rank:92, artist:"Phoebe Bridgers",   album:"Punisher",                               year:2020 },
  { rank:93, artist:"Mitski",            album:"Be the Cowboy",                          year:2018 },
  { rank:94, artist:"Arctic Monkeys",    album:"AM",                                     year:2013 },
  { rank:95, artist:"Billie Eilish",     album:"When We All Fall Asleep, Where Do We Go?", year:2019 },
];

export const LOCAL_DB = [
  { artist:"The Beatles",        album:"Abbey Road",                      year:1969 },
  { artist:"The Rolling Stones", album:"Exile on Main St.",               year:1972 },
  { artist:"Led Zeppelin",       album:"Led Zeppelin IV",                 year:1971 },
  { artist:"Pink Floyd",         album:"The Dark Side of the Moon",       year:1973 },
  { artist:"Radiohead",          album:"OK Computer",                     year:1997 },
  { artist:"David Bowie",        album:"Ziggy Stardust",                  year:1972 },
  { artist:"Nirvana",            album:"Nevermind",                       year:1991 },
  { artist:"Fleetwood Mac",      album:"Rumours",                         year:1977 },
  { artist:"Bob Dylan",          album:"Blood on the Tracks",             year:1975 },
  { artist:"The Smiths",         album:"The Queen Is Dead",               year:1986 },
  { artist:"Joy Division",       album:"Unknown Pleasures",               year:1979 },
  { artist:"Arctic Monkeys",     album:"AM",                              year:2013 },
  { artist:"Kendrick Lamar",     album:"To Pimp a Butterfly",             year:2015 },
  { artist:"Taylor Swift",       album:"Folklore",                        year:2020 },
  { artist:"Beyonce",            album:"Lemonade",                        year:2016 },
  { artist:"Kanye West",         album:"My Beautiful Dark Twisted Fantasy", year:2010 },
  { artist:"Frank Ocean",        album:"Blonde",                          year:2016 },
  { artist:"Amy Winehouse",      album:"Back to Black",                   year:2006 },
  { artist:"The Strokes",        album:"Is This It",                      year:2001 },
  { artist:"LCD Soundsystem",    album:"Sound of Silver",                 year:2007 },
  { artist:"Arcade Fire",        album:"Funeral",                         year:2004 },
  { artist:"Phoebe Bridgers",    album:"Punisher",                        year:2020 },
  { artist:"Tyler, the Creator", album:"Igor",                            year:2019 },
  { artist:"Portishead",         album:"Dummy",                           year:1994 },
  { artist:"Daft Punk",          album:"Discovery",                       year:2001 },
  { artist:"Charli XCX",         album:"Brat",                            year:2024 },
  { artist:"SZA",                album:"SOS",                             year:2022 },
  { artist:"Fontaines D.C.",     album:"Romance",                         year:2024 },
];
